# Generated by Django 5.2.8 on 2026-04-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_person_api_person_gender_851d2c_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='sample_size',
        ),
    ]
